### ISSUE TITLE
The 2500 is the total for group B, not the number of non-members

### ISSUE THREAD

**Issue by karl-project-review** [madengr00/intro-data-capstone-biodiversity#10]
https://github.com/madengr00/intro-data-capstone-biodiversity/blob/622ea014dbed8800122c759ee0cc37dfa14d8a49/musclehub.py#L377
Looks like the wrong item was copied into the contingency table, as the 2500 should be 2250 (which is the number of non-members in group B). Be sure to double check when copying over values to avoid these sorts of errors.

**Comment by madengr00** [comment]
Yes.  Thank You. 
Question.  Is there a "Pythonic" way to generate a contingency table?  In this case there were only four values, but if we had a larger table to analyze,  then manually entering could be even more prone to errors.

**Comment by karl-project-review** [comment]
Sure, we can reference the particular elements in the DataFrame rather than copying them. Below is sample code that would build the contingency table for this problem, and that would also work if we added an arbitrary number of additional test groups. It creates an empty list (our contingency table), and then inserts a new sublist into the table for each row in final_member_pivot. 
```python
contingency = []
for i in range(0, len(final_member_pivot)):
    contingency.append([final_member_pivot['Member'][i], final_member_pivot['Not Member'][i]])
```
