### ISSUE TITLE
This import is a duplicate

### ISSUE THREAD

**Issue by karl-project-review** [madengr00/intro-data-capstone-biodiversity#11]
https://github.com/madengr00/intro-data-capstone-biodiversity/blob/622ea014dbed8800122c759ee0cc37dfa14d8a49/musclehub.py#L330
This import statement was already made in line 265 above. It can be useful to put all import statements in one place at the top of the file to make it easier to avoid importing the same libraries multiple times.

**Comment by madengr00** [comment]
Great tip!  Thanks.
