### ISSUE TITLE
Put plt.savefig() before plt.show()

### ISSUE THREAD

**Issue by karl-project-review** [madengr00/intro-data-capstone-biodiversity#7]
https://github.com/madengr00/intro-data-capstone-biodiversity/blob/622ea014dbed8800122c759ee0cc37dfa14d8a49/musclehub.py#L189-L190
I am guessing that the images of your charts saved with plt.savefig() were blank? If so, this is because calling plt.show() clears the figures after they are displayed. If we call plt.savefig() before calling plt.show(), though, the figures will be saved properly.

**Comment by madengr00** [comment]
Thank you.  I have moved them and they now appear to save correctly.
